import { fileURLToPath } from "node:url";

import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

export default defineConfig({
  extends: [core],
  jsPlugins: [
    "@shadcn/lint",
    {
      name: "executor",
      specifier: fileURLToPath(
        new URL("scripts/oxlint-plugin-executor.js", import.meta.url),
      ),
    },
  ],
  ignorePatterns: [...(core.ignorePatterns ?? []), "**/Generated.ts"],
  rules: {
    complexity: "off",
    eqeqeq: ["error", "smart"],
    "func-names": "off",
    "func-style": "off",
    "max-classes-per-file": "off",
    "no-alert": "off",
    "no-await-in-loop": "off",
    "no-empty-function": "off",
    "no-eq-null": "off",
    "no-inline-comments": "off",
    "no-negated-condition": "off",
    "no-nested-ternary": "off",
    "no-param-reassign": "off",
    "no-plusplus": "off",
    "no-redeclare": "off",
    "no-shadow": "off",
    "no-unused-vars": "off",
    "no-use-before-define": "off",
    "no-warning-comments": "off",
    "prefer-destructuring": "off",
    "prefer-named-capture-group": "off",
    "require-unicode-regexp": "off",
    "sort-keys": "off",
    "oxc/no-barrel-file": "off",
    "promise/prefer-await-to-callbacks": "off",

    "shadcn/no-arbitrary-values": "error",
    "shadcn/no-inline-styles": "error",
    "shadcn/no-raw-colors": "error",
    "shadcn/no-restyle": "error",
    "shadcn/no-unknown-classes": "error",
    "shadcn/require-static-classes": "error",

    "typescript/consistent-type-definitions": "off",
    "typescript/no-dynamic-delete": "off",
    "typescript/no-non-null-assertion": "off",

    "executor/no-conditional-tests": "error",
    "executor/no-double-cast": "error",
    "executor/no-effect-escape-hatch": "error",
    "executor/no-effect-internal-tags": "error",
    "executor/no-error-constructor": "error",
    "executor/no-inline-schema-compile": "error",
    "executor/no-instanceof-error": "error",
    "executor/no-instanceof-tagged-error": "error",
    "executor/no-json-parse": "error",
    "executor/no-manual-tag-check": "error",
    "executor/no-match-orelse": "error",
    "executor/no-promise-catch": "error",
    "executor/no-promise-reject": "error",
    "executor/no-raw-fetch": "error",
    "executor/no-redundant-error-factory": "error",
    "executor/no-redundant-primitive-cast": "error",
    "executor/no-schema-class": "error",
    "executor/no-switch-statement": "error",
    "executor/no-try-catch-or-throw": "error",
    "executor/no-ts-nocheck": "error",
    "executor/no-unknown-error-message": "error",
    "executor/no-unsupported-effect-api": "error",
    "executor/no-vitest-import": "error",
    "executor/prefer-effect-predicate": "error",
    "executor/prefer-schema-inferred-types": "error",
    "executor/prefer-value-inferred-extension-types": "error",
    "executor/prefer-yield-tagged-error": "error",

    "unicorn/catch-error-name": "off",
    "unicorn/consistent-function-scoping": "off",
    "unicorn/custom-error-definition": "off",
    "unicorn/filename-case": "off",
    "unicorn/no-anonymous-default-export": "off",
    "unicorn/no-array-method-this-argument": "off",
    "unicorn/no-array-reduce": "off",
    "unicorn/no-array-sort": "off",
    "unicorn/no-document-cookie": "off",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/prefer-number-coercion": "off",
    "unicorn/prefer-string-slice": "off",
    "unicorn/throw-new-error": "off",
  },
  settings: {
    shadcn: {
      ui: "@/components/ui",
      componentImports: ["(?:^|/)components/ui(/|$)", "^@foldkit/ui(/|$)"],
    },
  },
  overrides: [
    {
      files: ["scripts/**/*.{ts,js}"],
      rules: {
        "executor/no-effect-escape-hatch": "off",
        "executor/no-error-constructor": "off",
        "executor/no-instanceof-error": "off",
        "executor/no-json-parse": "off",
        "executor/no-promise-catch": "off",
        "executor/no-promise-reject": "off",
        "executor/no-switch-statement": "off",
        "executor/no-try-catch-or-throw": "off",
        "executor/no-unknown-error-message": "off",
      },
    },
  ],
});
