/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as AuthedIndexImport } from './routes/_authed.index'
import { Route as AuthedWorkoutsImport } from './routes/_authed.workouts'
import { Route as AuthedAnalyticsImport } from './routes/_authed.analytics'
import { Route as AuthedWorkoutsIndexImport } from './routes/_authed.workouts.index'
import { Route as AuthedWorkoutsNewImport } from './routes/_authed.workouts.new'
import { Route as AuthedCalendarSplatImport } from './routes/_authed.calendar.$'
import { Route as AuthedWorkoutsEditIdImport } from './routes/_authed.workouts.edit.$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const AuthedIndexRoute = AuthedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedWorkoutsRoute = AuthedWorkoutsImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAnalyticsRoute = AuthedAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedWorkoutsIndexRoute = AuthedWorkoutsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWorkoutsRoute,
} as any)

const AuthedWorkoutsNewRoute = AuthedWorkoutsNewImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedWorkoutsRoute,
} as any)

const AuthedCalendarSplatRoute = AuthedCalendarSplatImport.update({
  id: '/calendar/$',
  path: '/calendar/$',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedWorkoutsEditIdRoute = AuthedWorkoutsEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthedWorkoutsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/workouts': {
      id: '/_authed/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthedWorkoutsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/calendar/$': {
      id: '/_authed/calendar/$'
      path: '/calendar/$'
      fullPath: '/calendar/$'
      preLoaderRoute: typeof AuthedCalendarSplatImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/workouts/new': {
      id: '/_authed/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof AuthedWorkoutsNewImport
      parentRoute: typeof AuthedWorkoutsImport
    }
    '/_authed/workouts/': {
      id: '/_authed/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthedWorkoutsIndexImport
      parentRoute: typeof AuthedWorkoutsImport
    }
    '/_authed/workouts/edit/$id': {
      id: '/_authed/workouts/edit/$id'
      path: '/edit/$id'
      fullPath: '/workouts/edit/$id'
      preLoaderRoute: typeof AuthedWorkoutsEditIdImport
      parentRoute: typeof AuthedWorkoutsImport
    }
  }
}

// Create and export the route tree

interface AuthedWorkoutsRouteChildren {
  AuthedWorkoutsNewRoute: typeof AuthedWorkoutsNewRoute
  AuthedWorkoutsIndexRoute: typeof AuthedWorkoutsIndexRoute
  AuthedWorkoutsEditIdRoute: typeof AuthedWorkoutsEditIdRoute
}

const AuthedWorkoutsRouteChildren: AuthedWorkoutsRouteChildren = {
  AuthedWorkoutsNewRoute: AuthedWorkoutsNewRoute,
  AuthedWorkoutsIndexRoute: AuthedWorkoutsIndexRoute,
  AuthedWorkoutsEditIdRoute: AuthedWorkoutsEditIdRoute,
}

const AuthedWorkoutsRouteWithChildren = AuthedWorkoutsRoute._addFileChildren(
  AuthedWorkoutsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedWorkoutsRoute: typeof AuthedWorkoutsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCalendarSplatRoute: typeof AuthedCalendarSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedWorkoutsRoute: AuthedWorkoutsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCalendarSplatRoute: AuthedCalendarSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/workouts': typeof AuthedWorkoutsRouteWithChildren
  '/': typeof AuthedIndexRoute
  '/calendar/$': typeof AuthedCalendarSplatRoute
  '/workouts/new': typeof AuthedWorkoutsNewRoute
  '/workouts/': typeof AuthedWorkoutsIndexRoute
  '/workouts/edit/$id': typeof AuthedWorkoutsEditIdRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/': typeof AuthedIndexRoute
  '/calendar/$': typeof AuthedCalendarSplatRoute
  '/workouts/new': typeof AuthedWorkoutsNewRoute
  '/workouts': typeof AuthedWorkoutsIndexRoute
  '/workouts/edit/$id': typeof AuthedWorkoutsEditIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/workouts': typeof AuthedWorkoutsRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/calendar/$': typeof AuthedCalendarSplatRoute
  '/_authed/workouts/new': typeof AuthedWorkoutsNewRoute
  '/_authed/workouts/': typeof AuthedWorkoutsIndexRoute
  '/_authed/workouts/edit/$id': typeof AuthedWorkoutsEditIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/analytics'
    | '/workouts'
    | '/'
    | '/calendar/$'
    | '/workouts/new'
    | '/workouts/'
    | '/workouts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/'
    | '/calendar/$'
    | '/workouts/new'
    | '/workouts'
    | '/workouts/edit/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/analytics'
    | '/_authed/workouts'
    | '/_authed/'
    | '/_authed/calendar/$'
    | '/_authed/workouts/new'
    | '/_authed/workouts/'
    | '/_authed/workouts/edit/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authed",
        "/login"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/analytics",
        "/_authed/workouts",
        "/_authed/",
        "/_authed/calendar/$"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/analytics": {
      "filePath": "_authed.analytics.tsx",
      "parent": "/_authed"
    },
    "/_authed/workouts": {
      "filePath": "_authed.workouts.tsx",
      "parent": "/_authed",
      "children": [
        "/_authed/workouts/new",
        "/_authed/workouts/",
        "/_authed/workouts/edit/$id"
      ]
    },
    "/_authed/": {
      "filePath": "_authed.index.tsx",
      "parent": "/_authed"
    },
    "/_authed/calendar/$": {
      "filePath": "_authed.calendar.$.tsx",
      "parent": "/_authed"
    },
    "/_authed/workouts/new": {
      "filePath": "_authed.workouts.new.tsx",
      "parent": "/_authed/workouts"
    },
    "/_authed/workouts/": {
      "filePath": "_authed.workouts.index.tsx",
      "parent": "/_authed/workouts"
    },
    "/_authed/workouts/edit/$id": {
      "filePath": "_authed.workouts.edit.$id.tsx",
      "parent": "/_authed/workouts"
    }
  }
}
ROUTE_MANIFEST_END */
