/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedWorkoutsRouteImport } from './routes/_authed.workouts'
import { Route as AuthedAnalyticsRouteImport } from './routes/_authed.analytics'
import { Route as AuthedWorkoutsIndexRouteImport } from './routes/_authed.workouts.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AuthedWorkoutsNewRouteImport } from './routes/_authed.workouts.new'
import { Route as AuthedCalendarSplatRouteImport } from './routes/_authed.calendar.$'
import { Route as AuthedWorkoutsEditIdRouteImport } from './routes/_authed.workouts.edit.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsRoute = AuthedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAnalyticsRoute = AuthedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsIndexRoute = AuthedWorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedWorkoutsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkoutsNewRoute = AuthedWorkoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedWorkoutsRoute,
} as any)
const AuthedCalendarSplatRoute = AuthedCalendarSplatRouteImport.update({
  id: '/calendar/$',
  path: '/calendar/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWorkoutsEditIdRoute = AuthedWorkoutsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AuthedWorkoutsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/workouts': typeof AuthedWorkoutsRouteWithChildren
  '/calendar/$': typeof AuthedCalendarSplatRoute
  '/workouts/new': typeof AuthedWorkoutsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workouts/': typeof AuthedWorkoutsIndexRoute
  '/workouts/edit/$id': typeof AuthedWorkoutsEditIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/analytics': typeof AuthedAnalyticsRoute
  '/': typeof AuthedIndexRoute
  '/calendar/$': typeof AuthedCalendarSplatRoute
  '/workouts/new': typeof AuthedWorkoutsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/workouts': typeof AuthedWorkoutsIndexRoute
  '/workouts/edit/$id': typeof AuthedWorkoutsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/analytics': typeof AuthedAnalyticsRoute
  '/_authed/workouts': typeof AuthedWorkoutsRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/calendar/$': typeof AuthedCalendarSplatRoute
  '/_authed/workouts/new': typeof AuthedWorkoutsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/workouts/': typeof AuthedWorkoutsIndexRoute
  '/_authed/workouts/edit/$id': typeof AuthedWorkoutsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/workouts'
    | '/calendar/$'
    | '/workouts/new'
    | '/api/auth/$'
    | '/workouts/'
    | '/workouts/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/analytics'
    | '/'
    | '/calendar/$'
    | '/workouts/new'
    | '/api/auth/$'
    | '/workouts'
    | '/workouts/edit/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/analytics'
    | '/_authed/workouts'
    | '/_authed/'
    | '/_authed/calendar/$'
    | '/_authed/workouts/new'
    | '/api/auth/$'
    | '/_authed/workouts/'
    | '/_authed/workouts/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts': {
      id: '/_authed/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthedWorkoutsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/analytics': {
      id: '/_authed/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthedAnalyticsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/': {
      id: '/_authed/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthedWorkoutsIndexRouteImport
      parentRoute: typeof AuthedWorkoutsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workouts/new': {
      id: '/_authed/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof AuthedWorkoutsNewRouteImport
      parentRoute: typeof AuthedWorkoutsRoute
    }
    '/_authed/calendar/$': {
      id: '/_authed/calendar/$'
      path: '/calendar/$'
      fullPath: '/calendar/$'
      preLoaderRoute: typeof AuthedCalendarSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/workouts/edit/$id': {
      id: '/_authed/workouts/edit/$id'
      path: '/edit/$id'
      fullPath: '/workouts/edit/$id'
      preLoaderRoute: typeof AuthedWorkoutsEditIdRouteImport
      parentRoute: typeof AuthedWorkoutsRoute
    }
  }
}

interface AuthedWorkoutsRouteChildren {
  AuthedWorkoutsNewRoute: typeof AuthedWorkoutsNewRoute
  AuthedWorkoutsIndexRoute: typeof AuthedWorkoutsIndexRoute
  AuthedWorkoutsEditIdRoute: typeof AuthedWorkoutsEditIdRoute
}

const AuthedWorkoutsRouteChildren: AuthedWorkoutsRouteChildren = {
  AuthedWorkoutsNewRoute: AuthedWorkoutsNewRoute,
  AuthedWorkoutsIndexRoute: AuthedWorkoutsIndexRoute,
  AuthedWorkoutsEditIdRoute: AuthedWorkoutsEditIdRoute,
}

const AuthedWorkoutsRouteWithChildren = AuthedWorkoutsRoute._addFileChildren(
  AuthedWorkoutsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAnalyticsRoute: typeof AuthedAnalyticsRoute
  AuthedWorkoutsRoute: typeof AuthedWorkoutsRouteWithChildren
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedCalendarSplatRoute: typeof AuthedCalendarSplatRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAnalyticsRoute: AuthedAnalyticsRoute,
  AuthedWorkoutsRoute: AuthedWorkoutsRouteWithChildren,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedCalendarSplatRoute: AuthedCalendarSplatRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
